# Sample .travis.yml for R projects.
# Via https://docs.travis-ci.com/user/languages/r/

language: r
cache: packages
sudo: false
bioc_packages:
 - hopach
 - multtest

r_github_packages:
 - jimhester/covr

after_success:
 - Rscript -e 'covr::codecov()'

# Allow build to take up to 30 minutes without returning output (esp. during example testing)
script:
  - |
    R CMD build .
    travis_wait 30 R CMD check varImpact_1.2.tar.gz

# Get error logs in case of failure.
after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;
