# Docs: https://docs.travis-ci.com/user/languages/r/
# Validate your .travis.yml file at http://lint.travis-ci.org/

language: r
cache: packages
sudo: false

# Install nlopt package to help nloptr install.
addons:
  apt:
    packages:
      - libnlopt-dev

#r_github_packages:
#  - jimhester/covr

r_packages:
  - covr

bioc_packages:
 - hopach
 - multtest

# Test on 3 versions of R.
r:
  - release
  - devel
  - oldrel

env:
  global:
    # Allow build to continue even if a suggested package cannot be installed.
    - _R_CHECK_FORCE_SUGGESTS_=false

matrix:
  # Report build completion status once non-"allow_failures" builds are done.
  fast_finish: true
  # Allow failures on OSX.
  allow_failures:
    - os: osx

# Allow build to take up to 40 minutes without returning output (esp. during example testing)
# Without this section, travis build will fail to lack of output for 10 minutes.
script:
  - |
    R CMD build .
    travis_wait 40 R CMD check varImpact*.tar.gz

# code coverage testing is timing out after 10 minutes, also need to
# enable travis_wait for this.
#after_success:
  # Only check test coverage for R = release and OS = linux.
#  - test ${TRAVIS_R_VERSION_STRING} == "release" && test ${TRAVIS_OS_NAME} == "linux" && Rscript -e 'covr::codecov()'

# Get error logs in case of failure.
after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;
