# Sample .travis.yml for R projects.
# Via https://docs.travis-ci.com/user/languages/r/

language: r
cache: packages
sudo: false

# Install nlopt package to help nloptr install.
addons:
  apt:
    packages:
      - libnlopt-dev

#r_github_packages:
#  - jimhester/covr

r_packages:
  - covr

bioc_packages:
 - hopach
 - multtest

#after_success:
 #- Rscript -e 'covr::codecov()'

# Allow build to take up to 40 minutes without returning output (esp. during example testing)
script:
  - |
    R CMD build .
    travis_wait 40 R CMD check varImpact*.tar.gz

# Get error logs in case of failure.
after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;
